# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Richard Szczerba
tagline:          ''
description:      ''
url:              http://http://enymuss.github.io/

author:
  name:           'Richard Szczerba'
  url:            ''

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
